packages: []

catalogs:
  build:
    tsx: ^4.21.0
    unocss: ^66.6.0
  dev:
    '@antfu/eslint-config': ^5.4.1
    '@iconify/json': ^2.2.436
    '@nuxt/test-utils': ^3.23.0
    '@unocss/eslint-plugin': 0.65.2
    '@unocss/nuxt': ^66.6.0
    '@vitest/coverage-v8': ^3.2.4
    '@vitest/ui': ^3.2.4
    '@vue/test-utils': ^2.4.6
    '@vueuse/core': ^13.9.0
    '@vueuse/nuxt': ^13.9.0
    '@vueuse/router': ^13.9.0
    eslint: ^9.39.2
    eslint-plugin-format: ^1.4.0
    happy-dom: ^20.5.0
    lint-staged: ^16.2.7
    playwright-core: ^1.58.2
    simple-git-hooks: ^2.13.1
    vitest: ^3.2.4
  frontend:
    '@nuxt/content': ^3.11.2
    '@nuxtjs/color-mode': ^3.5.2
    dayjs-nuxt: ^2.1.11
    nuxt: ^4.3.0
    vue: ^3.5.27
    vue-router: ^4.6.4
  server:
    '@libsql/client': ^0.15.15
    better-sqlite3: ^12.6.2
    drizzle-kit: ^0.31.8
    drizzle-orm: ^0.44.7
  shared:
    better-auth: ^1.4.18
  types:
    '@types/better-sqlite3': ^7.6.13
onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - esbuild
  - simple-git-hooks
